apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleepapi
spec:
  selector:
    matchLabels:
      app: sleepapi
  replicas: 1
  template:
    metadata:
      labels:
        app: sleepapi
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: sleepapi
        image: lakmatiol.azurecr.io/sleepapi:latest
        ports:
        - containerPort: 8080
