name: ci
on:
    push:
        branches: master

jobs:
    push:
        runs-on: ubuntu-latest
        steps:
        - name: Check out the repo
          uses: actions/checkout@v2
        - name: Push to ACR
          uses: docker/build-push-action@v1
          with:
              registry: lakmatiol.azurecr.io
              username: ${{ secrets.ACR_LOGIN }}
              password: ${{ secrets.ACR_passwd }}

