name: ci
on:
    push:
        branches: master
    workflow_dispatch:

jobs:
    push:
        runs-on: ubuntu-latest
        steps:
        - name: Check out the repo
          uses: actions/checkout@v2

        - name: Login to ACR
          uses: docker/login-action@v1
          with:
              registry: lakmatiol.azurecr.io
              username: ${{ secrets.ACR_LOGIN }}
              password: ${{ secrets.ACR_PASSWD }}

        - name: Push to ACR
          uses: docker/build-push-action@v2
          with:
              push: true
              tags: sleepapi:latest

